name: dozacountres
version: '1.0.0'
main: dev.doza.dozacountres.Dozacountres
api-version: '1.21'
commands:
  country:
    usage: /<command> <arg>
dependencies:
  server:
    WorldGuard:
      load: BEFORE
      required: true
permissions:
  dozacountries.command:
    description: право на использование команды плагина
    default: op
